# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_forum', '0014_auto_20170202_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='votes',
        ),
        migrations.AddField(
            model_name='topic',
            name='no_of_down_votes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='topic',
            name='no_of_votes',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
