# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_forum', '0016_auto_20170203_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(to='django_simple_forum.Vote'),
        ),
    ]
